### ISSUE TITLE
Request: Please add instructions how to run this repo

### ISSUE THREAD

**Issue by Apurva-tech** [S-Bobbiti/PathPlanning-GeneticAlgorithm#1]
- It will be really helpful if you could add instructions on how to run this repo, and the pre-requisites required

**Comment by Apurva-tech** [comment]
And could you also please specify what versions of the libraries have you used

**Comment by S-Bobbiti** [comment]
Hi Apurva, I have updated the instructions. For further details about the algorithms' configuration, please check the paper, i.e., the pdf file in the repository.
